# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_url',
            field=models.CharField(default='https://www.chattrics.com/', max_length=100),
            preserve_default=False,
        ),
    ]
